[dataset]
name = "FActscore"
train_percent = 0.3
valid_percent = 0.4 
# n = 10 # comment to use the whole dataset
randomize = false
seed = 0


[model.parser]
name = "gpt-4-0125-preview"
max_tokens = 1000
temperature = 0
n_samples = 1

[model.annotator]
name = "gpt-4-0125-preview"
max_tokens = 1000
temperature = 0
n_samples = 1

[model.responder]
name = "gpt-3.5-turbo"
max_tokens = 1000
temperature = 0
n_samples = 1

[conformal]
alpha = 0.3
